### ISSUE TITLE
Compile art work from Instagram and add to the repo

### ISSUE THREAD

**Issue by Goose-Of-War** [kgpmask/MASK#105]
Go to [our Instagram account](https://www.instagram.com/maskiitkgp), get the images and store them in the `assets` folder. 

Please don't take a screenshot of the image. You can find the source image if you search properly. Remember to compress it to less than 200kb

**Comment by PartMan7** [comment]
Can I close this now?

**Comment by ItsAnkan** [comment]
yes... i think, dimensions are mentioned in the img tag now

**Comment by Goose-Of-War** [comment]
Yup, good to close
