### ISSUE TITLE
Newsletter JS repositioning

### ISSUE THREAD

**Issue by Goose-Of-War** [kgpmask/MASK#110]
The code of the scripts for crossword and word search is present in every other newsletter njk file. @MokshithPV your task is to make sure you move as much as possible in `_newsletter.njk`.

Your work will mostly be in `{% block letterjs %}`. You can edit `{% block prescript %}` too, but I don't think it's necessary. This task's priority is moderate, since Jai will be working on newsletters soon after you're done.

**Comment by PartMan7** [comment]
Personally I'd say use a macro instead

**Comment by Goose-Of-War** [comment]
Closed a while back itself ig
