### ISSUE TITLE
Newsletter Landing Page Front-End Revamp

### ISSUE THREAD

**Issue by Goose-Of-War** [kgpmask/MASK#165]
> Not #57 

With more and more newsletters coming, the page size changes a lot when you expand a given year's accordion panel (list of months and issues).  
Therefore, we need a newer design for the same, preferably using the cover pages if possible.

**Comment by ItsAnkan** [comment]
im thinking something like this ?
![image](https://github.com/kgpmask/MASK/assets/93087057/6fa9af30-d174-4276-b4b4-ceb1304037a1)

**Comment by ItsAnkan** [comment]
yea... ig
and then we can have a scrollable area for the other ones, either order monthwise, or do something like it is now

**Comment by Goose-Of-War** [comment]
Interesting... Go ahead.

**Comment by ItsAnkan** [comment]
This issue is done ig ?

**Comment by Goose-Of-War** [comment]
Ah yes. Since we changed PRs, I think this one got missed out. Closing it
