### ISSUE TITLE
Members list update

### ISSUE THREAD

**Issue by nishkalprakash** [kgpmask/MASK#194]
- Members list should be updated to reflect the latest changes

**Comment by Goose-Of-War** [comment]
Wdym?

**Comment by nishkalprakash** [comment]
- like making you webd head?
- yeeting folks who left the soc. (maybe move them to "former members"?)

**Comment by nishkalprakash** [comment]
maybe we can also include a feature/new page "our teams" to have a view by team ?
like all webd folks together in a group,
if you're in multiple team then you appear multiple times
this would be cool.

**Comment by Goose-Of-War** [comment]
> maybe we can also include a feature/new page "our teams" to have a view by team ?
> like all webd folks together in a group,
> if you're in multiple team then you appear multiple times
> this would be cool.

Let the promotion announcement come out first...
