### ISSUE TITLE
Too many quiz templates

### ISSUE THREAD

**Issue by Goose-Of-War** [kgpmask/MASK#61]

**Comment by nishkalprakash** [comment]
Perhaps assign someone else for this?

**Comment by Goose-Of-War** [comment]
It was yours, but you're going underground, so...
_sigh_

**Comment by Goose-Of-War** [comment]
PS: It would be preferrable to isolate `generateHTML` since we might use it somewhere else except for the quiz templates (preferably a JS file in `/assets` which we can call?

**Comment by nishkalprakash** [comment]
can u also set a feasible deadline 
onegai

**Comment by Goose-Of-War** [comment]
Let's see... How's Thursday EoD sounding?

**Comment by nishkalprakash** [comment]
ok

**Comment by Goose-Of-War** [comment]
> opened on Feb 1
😶‍🌫️

**Comment by Goose-Of-War** [comment]
Close this ig, since quizzes ain't gon be done no more unless it's Live
