### ISSUE TITLE
Newsletter to be done using `{% include template %}`

### ISSUE THREAD

**Issue by Goose-Of-War** [kgpmask/MASK#67]
This one needs to be done somewhat soon

**Comment by nishkalprakash** [comment]
How soon?

**Comment by Goose-Of-War** [comment]
Before the March one

**Comment by Goose-Of-War** [comment]
So around a month?

**Comment by nishkalprakash** [comment]
Phew
I thought you'd say by 12 today.

**Comment by nishkalprakash** [comment]
@Goose-Of-War Have done the task.
Please review and pull to dev.

**Comment by nishkalprakash** [comment]
branch is `newsletter-ocd-fix`

**Comment by Goose-Of-War** [comment]
Make PR

**Comment by Goose-Of-War** [comment]
Will review once and then merge and close
