### ISSUE TITLE
Error handler (currently on dev) doesn't catch errors

### ISSUE THREAD

**Issue by PartMan7** [kgpmask/MASK#72]
Make it actually detect errors and send a 500, then add a hardcoded route that throws an Error and store this in tests

**Comment by PartMan7** [comment]
Fixed

**Comment by PartMan7** [comment]
Well sorry, code is done but not in this one

**Comment by PartMan7** [comment]
@SachdevJai any update on this?

**Comment by SachdevJai** [comment]
Yes im working on getting the error page to show up 

Ill try to push by eod

**Comment by PartMan7** [comment]
Thanks!
